// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AcknowledgeAlertData, AcknowledgeAlertErrors, AcknowledgeAlertResponses, CancelExecutionData, CancelExecutionErrors, CancelExecutionResponses, CreateAlertData, CreateAlertErrors, CreateAlertResponses, CreateWorkflowData, CreateWorkflowErrors, CreateWorkflowResponses, DeleteWorkflowData, DeleteWorkflowErrors, DeleteWorkflowResponses, ExecuteWorkflowData, ExecuteWorkflowErrors, ExecuteWorkflowResponses, GetAlertData, GetAlertErrors, GetAlertResponses, GetExecutionData, GetExecutionErrors, GetExecutionResponses, GetWorkflowData, GetWorkflowErrors, GetWorkflowResponses, HealthCheckData, HealthCheckErrors, HealthCheckResponses, ListAlertsData, ListAlertsErrors, ListAlertsResponses, ListAuditLogsByResourceData, ListAuditLogsByResourceErrors, ListAuditLogsByResourceResponses, ListAuditLogsByUserData, ListAuditLogsByUserErrors, ListAuditLogsByUserResponses, ListAuditLogsData, ListAuditLogsErrors, ListAuditLogsResponses, ListExecutionsData, ListExecutionsErrors, ListExecutionsResponses, ListWorkflowExecutionsData, ListWorkflowExecutionsErrors, ListWorkflowExecutionsResponses, ListWorkflowsData, ListWorkflowsErrors, ListWorkflowsResponses, LivenessProbeData, LivenessProbeErrors, LivenessProbeResponses, ReadinessProbeData, ReadinessProbeErrors, ReadinessProbeResponses, ResolveAlertData, ResolveAlertErrors, ResolveAlertResponses, UpdateWorkflowData, UpdateWorkflowErrors, UpdateWorkflowResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 *
 * Returns the overall health status of the service
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({ url: '/health', ...options });

/**
 * Liveness probe
 *
 * Kubernetes liveness probe endpoint
 */
export const livenessProbe = <ThrowOnError extends boolean = false>(options?: Options<LivenessProbeData, ThrowOnError>) => (options?.client ?? client).get<LivenessProbeResponses, LivenessProbeErrors, ThrowOnError>({ url: '/health/live', ...options });

/**
 * Readiness probe
 *
 * Kubernetes readiness probe endpoint
 */
export const readinessProbe = <ThrowOnError extends boolean = false>(options?: Options<ReadinessProbeData, ThrowOnError>) => (options?.client ?? client).get<ReadinessProbeResponses, ReadinessProbeErrors, ThrowOnError>({ url: '/health/ready', ...options });

/**
 * List workflows
 *
 * Returns a paginated list of workflows for the current tenant
 */
export const listWorkflows = <ThrowOnError extends boolean = false>(options?: Options<ListWorkflowsData, ThrowOnError>) => (options?.client ?? client).get<ListWorkflowsResponses, ListWorkflowsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/workflows',
    ...options
});

/**
 * Create workflow
 *
 * Creates a new workflow definition
 */
export const createWorkflow = <ThrowOnError extends boolean = false>(options: Options<CreateWorkflowData, ThrowOnError>) => (options.client ?? client).post<CreateWorkflowResponses, CreateWorkflowErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/workflows',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete workflow
 *
 * Deletes a workflow by ID
 */
export const deleteWorkflow = <ThrowOnError extends boolean = false>(options: Options<DeleteWorkflowData, ThrowOnError>) => (options.client ?? client).delete<DeleteWorkflowResponses, DeleteWorkflowErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/workflows/{id}',
    ...options
});

/**
 * Get workflow
 *
 * Returns a single workflow by ID
 */
export const getWorkflow = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowData, ThrowOnError>) => (options.client ?? client).get<GetWorkflowResponses, GetWorkflowErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/workflows/{id}',
    ...options
});

/**
 * Update workflow
 *
 * Updates an existing workflow. Version is auto-incremented.
 */
export const updateWorkflow = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkflowData, ThrowOnError>) => (options.client ?? client).put<UpdateWorkflowResponses, UpdateWorkflowErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/workflows/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Execute workflow
 *
 * Triggers a new execution of the workflow
 */
export const executeWorkflow = <ThrowOnError extends boolean = false>(options: Options<ExecuteWorkflowData, ThrowOnError>) => (options.client ?? client).post<ExecuteWorkflowResponses, ExecuteWorkflowErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/workflows/{id}/execute',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List workflow executions
 *
 * Returns a paginated list of executions for a specific workflow
 */
export const listWorkflowExecutions = <ThrowOnError extends boolean = false>(options: Options<ListWorkflowExecutionsData, ThrowOnError>) => (options.client ?? client).get<ListWorkflowExecutionsResponses, ListWorkflowExecutionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/workflows/{id}/executions',
    ...options
});

/**
 * List executions
 *
 * Returns a paginated list of all executions for the current tenant
 */
export const listExecutions = <ThrowOnError extends boolean = false>(options?: Options<ListExecutionsData, ThrowOnError>) => (options?.client ?? client).get<ListExecutionsResponses, ListExecutionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/executions',
    ...options
});

/**
 * Get execution
 *
 * Returns a single execution by ID
 */
export const getExecution = <ThrowOnError extends boolean = false>(options: Options<GetExecutionData, ThrowOnError>) => (options.client ?? client).get<GetExecutionResponses, GetExecutionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/executions/{id}',
    ...options
});

/**
 * Cancel execution
 *
 * Cancels a running execution
 */
export const cancelExecution = <ThrowOnError extends boolean = false>(options: Options<CancelExecutionData, ThrowOnError>) => (options.client ?? client).post<CancelExecutionResponses, CancelExecutionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/executions/{id}/cancel',
    ...options
});

/**
 * List alerts
 *
 * Returns a paginated list of alerts for the current tenant
 */
export const listAlerts = <ThrowOnError extends boolean = false>(options?: Options<ListAlertsData, ThrowOnError>) => (options?.client ?? client).get<ListAlertsResponses, ListAlertsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/alerts',
    ...options
});

/**
 * Create alert
 *
 * Creates a new alert
 */
export const createAlert = <ThrowOnError extends boolean = false>(options: Options<CreateAlertData, ThrowOnError>) => (options.client ?? client).post<CreateAlertResponses, CreateAlertErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/alerts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get alert
 *
 * Returns a single alert by ID
 */
export const getAlert = <ThrowOnError extends boolean = false>(options: Options<GetAlertData, ThrowOnError>) => (options.client ?? client).get<GetAlertResponses, GetAlertErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/alerts/{id}',
    ...options
});

/**
 * Acknowledge alert
 *
 * Marks an alert as acknowledged
 */
export const acknowledgeAlert = <ThrowOnError extends boolean = false>(options: Options<AcknowledgeAlertData, ThrowOnError>) => (options.client ?? client).post<AcknowledgeAlertResponses, AcknowledgeAlertErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/alerts/{id}/acknowledge',
    ...options
});

/**
 * Resolve alert
 *
 * Marks an alert as resolved
 */
export const resolveAlert = <ThrowOnError extends boolean = false>(options: Options<ResolveAlertData, ThrowOnError>) => (options.client ?? client).post<ResolveAlertResponses, ResolveAlertErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/alerts/{id}/resolve',
    ...options
});

/**
 * List audit logs
 *
 * Returns a paginated list of audit logs for the current tenant
 */
export const listAuditLogs = <ThrowOnError extends boolean = false>(options?: Options<ListAuditLogsData, ThrowOnError>) => (options?.client ?? client).get<ListAuditLogsResponses, ListAuditLogsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/audit-logs',
    ...options
});

/**
 * List audit logs by resource
 *
 * Returns a paginated list of audit logs for a specific resource
 */
export const listAuditLogsByResource = <ThrowOnError extends boolean = false>(options: Options<ListAuditLogsByResourceData, ThrowOnError>) => (options.client ?? client).get<ListAuditLogsByResourceResponses, ListAuditLogsByResourceErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/audit-logs/resource/{resourceType}/{resourceId}',
    ...options
});

/**
 * List audit logs by user
 *
 * Returns a paginated list of audit logs for a specific user
 */
export const listAuditLogsByUser = <ThrowOnError extends boolean = false>(options: Options<ListAuditLogsByUserData, ThrowOnError>) => (options.client ?? client).get<ListAuditLogsByUserResponses, ListAuditLogsByUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/audit-logs/user/{userId}',
    ...options
});
