// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api/v1' | 'https://api.orchestrix.io/v1' | (string & {});
};

/**
 * Health check response
 */
export type HealthStatus = {
    status: 'healthy' | 'unhealthy' | 'degraded';
    /**
     * Individual health checks
     */
    checks?: {
        [key: string]: {
            status?: string;
            message?: string;
        };
    };
};

/**
 * Workflow status
 */
export type WorkflowStatus = 'active' | 'inactive' | 'draft';

/**
 * Workflow definition for orchestration
 */
export type Workflow = {
    /**
     * Unique workflow identifier
     */
    id: string;
    /**
     * Tenant identifier
     */
    tenant_id: string;
    /**
     * Workflow name
     */
    name: string;
    /**
     * Optional workflow description
     */
    description?: string;
    /**
     * Workflow definition as JSON
     */
    definition: {
        [key: string]: unknown;
    };
    /**
     * Cron expression for scheduled execution (e.g., "0 * * * *" or "@daily")
     */
    schedule?: string;
    status: WorkflowStatus;
    /**
     * Version number (auto-incremented on update)
     */
    version: number;
    /**
     * User who created the workflow
     */
    created_by?: string;
    /**
     * Creation timestamp
     */
    created_at: string;
    /**
     * Last update timestamp
     */
    updated_at: string;
};

/**
 * Paginated list of workflows
 */
export type PaginatedWorkflows = {
    data: Array<Workflow>;
    /**
     * Total number of items
     */
    total: number;
    /**
     * Current page
     */
    page: number;
    /**
     * Items per page
     */
    limit: number;
};

/**
 * Error response
 */
export type Error = {
    /**
     * Error code
     */
    code: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Additional error details
     */
    details?: {
        [key: string]: unknown;
    };
};

/**
 * Request body for creating a workflow
 */
export type CreateWorkflowRequest = {
    /**
     * Workflow name
     */
    name: string;
    /**
     * Optional description
     */
    description?: string;
    /**
     * Workflow definition
     */
    definition: {
        [key: string]: unknown;
    };
    /**
     * Optional cron schedule
     */
    schedule?: string;
};

/**
 * Single workflow response wrapper
 */
export type WorkflowResponse = {
    data: Workflow;
};

/**
 * Request body for updating a workflow
 */
export type UpdateWorkflowRequest = {
    name?: string;
    description?: string;
    definition?: {
        [key: string]: unknown;
    };
    schedule?: string;
    status?: WorkflowStatus;
};

/**
 * Request body for executing a workflow
 */
export type ExecuteWorkflowRequest = {
    /**
     * Input data for the workflow execution
     */
    input?: {
        [key: string]: unknown;
    };
};

/**
 * Execution status
 */
export type ExecutionStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * Workflow execution instance
 */
export type Execution = {
    /**
     * Unique execution identifier
     */
    id: string;
    /**
     * Tenant identifier
     */
    tenant_id: string;
    /**
     * Parent workflow identifier
     */
    workflow_id: string;
    /**
     * Temporal workflow ID
     */
    temporal_workflow_id?: string;
    /**
     * Temporal run ID
     */
    temporal_run_id?: string;
    status: ExecutionStatus;
    /**
     * Input data provided at execution
     */
    input?: {
        [key: string]: unknown;
    };
    /**
     * Output data from execution
     */
    output?: {
        [key: string]: unknown;
    };
    /**
     * Error message if execution failed
     */
    error?: string;
    /**
     * Execution start time
     */
    started_at?: string;
    /**
     * Execution completion time
     */
    completed_at?: string;
    /**
     * User who triggered the execution
     */
    created_by?: string;
    /**
     * Creation timestamp
     */
    created_at: string;
};

/**
 * Single execution response wrapper
 */
export type ExecutionResponse = {
    data: Execution;
};

/**
 * Paginated list of executions
 */
export type PaginatedExecutions = {
    data: Array<Execution>;
    total: number;
    page: number;
    limit: number;
};

/**
 * Alert severity level
 */
export type AlertSeverity = 'info' | 'warning' | 'critical';

/**
 * Alert status
 */
export type AlertStatus = 'open' | 'acknowledged' | 'resolved';

/**
 * System alert for workflow events
 */
export type Alert = {
    /**
     * Unique alert identifier
     */
    id: string;
    /**
     * Tenant identifier
     */
    tenant_id: string;
    /**
     * Related workflow (if any)
     */
    workflow_id?: string;
    /**
     * Related execution (if any)
     */
    execution_id?: string;
    severity: AlertSeverity;
    /**
     * Alert title
     */
    title: string;
    /**
     * Detailed alert message
     */
    message?: string;
    status: AlertStatus;
    /**
     * When the alert was acknowledged
     */
    acknowledged_at?: string;
    /**
     * User who acknowledged
     */
    acknowledged_by?: string;
    /**
     * When the alert was resolved
     */
    resolved_at?: string;
    /**
     * User who resolved
     */
    resolved_by?: string;
    /**
     * Creation timestamp
     */
    created_at: string;
};

/**
 * Paginated list of alerts
 */
export type PaginatedAlerts = {
    data: Array<Alert>;
    total: number;
    page: number;
    limit: number;
};

/**
 * Request body for creating an alert
 */
export type CreateAlertRequest = {
    /**
     * Related workflow
     */
    workflow_id?: string;
    /**
     * Related execution
     */
    execution_id?: string;
    severity: AlertSeverity;
    title: string;
    /**
     * Detailed message
     */
    message?: string;
};

/**
 * Single alert response wrapper
 */
export type AlertResponse = {
    data: Alert;
};

/**
 * Audit log entry for tracking changes
 */
export type AuditLog = {
    /**
     * Unique audit log identifier
     */
    id: string;
    /**
     * Tenant identifier
     */
    tenant_id: string;
    /**
     * User who performed the action
     */
    user_id?: string;
    /**
     * Type of event
     */
    event_type: string;
    /**
     * Type of resource affected
     */
    resource_type: string;
    /**
     * ID of the affected resource
     */
    resource_id?: string;
    /**
     * Action performed
     */
    action: string;
    /**
     * Previous state of the resource
     */
    old_value?: {
        [key: string]: unknown;
    };
    /**
     * New state of the resource
     */
    new_value?: {
        [key: string]: unknown;
    };
    /**
     * Client IP address
     */
    ip_address?: string;
    /**
     * Client user agent
     */
    user_agent?: string;
    /**
     * When the event occurred
     */
    created_at: string;
};

/**
 * Paginated list of audit logs
 */
export type PaginatedAuditLogs = {
    data: Array<AuditLog>;
    total: number;
    page: number;
    limit: number;
};

/**
 * Page number (1-based)
 */
export type PageQuery = number;

/**
 * Number of items per page
 */
export type LimitQuery = number;

/**
 * Filter by workflow status
 */
export type WorkflowStatusQuery = 'active' | 'inactive' | 'draft';

/**
 * Search term
 */
export type SearchQuery = string;

/**
 * Resource UUID
 */
export type IdPath = string;

/**
 * Filter by execution status
 */
export type ExecutionStatusQuery = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * Filter by alert status
 */
export type AlertStatusQuery = 'open' | 'acknowledged' | 'resolved';

/**
 * Filter by event type
 */
export type EventTypeQuery = string;

/**
 * Type of resource (workflow, execution, alert)
 */
export type ResourceTypePath = 'workflow' | 'execution' | 'alert';

/**
 * Resource UUID
 */
export type ResourceIdPath = string;

/**
 * User UUID
 */
export type UserIdPath = string;

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckErrors = {
    /**
     * Service is unhealthy
     */
    503: HealthStatus;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * Service is healthy
     */
    200: HealthStatus;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type LivenessProbeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessProbeErrors = {
    /**
     * Service is not alive
     */
    503: HealthStatus;
};

export type LivenessProbeError = LivenessProbeErrors[keyof LivenessProbeErrors];

export type LivenessProbeResponses = {
    /**
     * Service is alive
     */
    200: HealthStatus;
};

export type LivenessProbeResponse = LivenessProbeResponses[keyof LivenessProbeResponses];

export type ReadinessProbeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessProbeErrors = {
    /**
     * Service is not ready
     */
    503: HealthStatus;
};

export type ReadinessProbeError = ReadinessProbeErrors[keyof ReadinessProbeErrors];

export type ReadinessProbeResponses = {
    /**
     * Service is ready
     */
    200: HealthStatus;
};

export type ReadinessProbeResponse = ReadinessProbeResponses[keyof ReadinessProbeResponses];

export type ListWorkflowsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Filter by workflow status
         */
        status?: 'active' | 'inactive' | 'draft';
        /**
         * Search term
         */
        search?: string;
    };
    url: '/workflows';
};

export type ListWorkflowsErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListWorkflowsError = ListWorkflowsErrors[keyof ListWorkflowsErrors];

export type ListWorkflowsResponses = {
    /**
     * List of workflows
     */
    200: PaginatedWorkflows;
};

export type ListWorkflowsResponse = ListWorkflowsResponses[keyof ListWorkflowsResponses];

export type CreateWorkflowData = {
    body: CreateWorkflowRequest;
    path?: never;
    query?: never;
    url: '/workflows';
};

export type CreateWorkflowErrors = {
    /**
     * Bad Request - Invalid input data
     */
    400: Error;
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Conflict - Resource already exists or state conflict
     */
    409: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type CreateWorkflowError = CreateWorkflowErrors[keyof CreateWorkflowErrors];

export type CreateWorkflowResponses = {
    /**
     * Workflow created successfully
     */
    201: WorkflowResponse;
};

export type CreateWorkflowResponse = CreateWorkflowResponses[keyof CreateWorkflowResponses];

export type DeleteWorkflowData = {
    body?: never;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/workflows/{id}';
};

export type DeleteWorkflowErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type DeleteWorkflowError = DeleteWorkflowErrors[keyof DeleteWorkflowErrors];

export type DeleteWorkflowResponses = {
    /**
     * No Content - Successful operation with no response body
     */
    204: void;
};

export type DeleteWorkflowResponse = DeleteWorkflowResponses[keyof DeleteWorkflowResponses];

export type GetWorkflowData = {
    body?: never;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/workflows/{id}';
};

export type GetWorkflowErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type GetWorkflowError = GetWorkflowErrors[keyof GetWorkflowErrors];

export type GetWorkflowResponses = {
    /**
     * Workflow found
     */
    200: WorkflowResponse;
};

export type GetWorkflowResponse = GetWorkflowResponses[keyof GetWorkflowResponses];

export type UpdateWorkflowData = {
    body: UpdateWorkflowRequest;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/workflows/{id}';
};

export type UpdateWorkflowErrors = {
    /**
     * Bad Request - Invalid input data
     */
    400: Error;
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type UpdateWorkflowError = UpdateWorkflowErrors[keyof UpdateWorkflowErrors];

export type UpdateWorkflowResponses = {
    /**
     * Workflow updated successfully
     */
    200: WorkflowResponse;
};

export type UpdateWorkflowResponse = UpdateWorkflowResponses[keyof UpdateWorkflowResponses];

export type ExecuteWorkflowData = {
    body?: ExecuteWorkflowRequest;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/workflows/{id}/execute';
};

export type ExecuteWorkflowErrors = {
    /**
     * Bad Request - Invalid input data
     */
    400: Error;
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Unprocessable Entity - Business rule violation
     */
    422: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ExecuteWorkflowError = ExecuteWorkflowErrors[keyof ExecuteWorkflowErrors];

export type ExecuteWorkflowResponses = {
    /**
     * Execution started
     */
    202: ExecutionResponse;
};

export type ExecuteWorkflowResponse = ExecuteWorkflowResponses[keyof ExecuteWorkflowResponses];

export type ListWorkflowExecutionsData = {
    body?: never;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Filter by execution status
         */
        status?: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
    };
    url: '/workflows/{id}/executions';
};

export type ListWorkflowExecutionsErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListWorkflowExecutionsError = ListWorkflowExecutionsErrors[keyof ListWorkflowExecutionsErrors];

export type ListWorkflowExecutionsResponses = {
    /**
     * List of executions
     */
    200: PaginatedExecutions;
};

export type ListWorkflowExecutionsResponse = ListWorkflowExecutionsResponses[keyof ListWorkflowExecutionsResponses];

export type ListExecutionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Filter by execution status
         */
        status?: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
    };
    url: '/executions';
};

export type ListExecutionsErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListExecutionsError = ListExecutionsErrors[keyof ListExecutionsErrors];

export type ListExecutionsResponses = {
    /**
     * List of executions
     */
    200: PaginatedExecutions;
};

export type ListExecutionsResponse = ListExecutionsResponses[keyof ListExecutionsResponses];

export type GetExecutionData = {
    body?: never;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/executions/{id}';
};

export type GetExecutionErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type GetExecutionError = GetExecutionErrors[keyof GetExecutionErrors];

export type GetExecutionResponses = {
    /**
     * Execution found
     */
    200: ExecutionResponse;
};

export type GetExecutionResponse = GetExecutionResponses[keyof GetExecutionResponses];

export type CancelExecutionData = {
    body?: never;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/executions/{id}/cancel';
};

export type CancelExecutionErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Cannot cancel - execution is not running
     */
    422: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type CancelExecutionError = CancelExecutionErrors[keyof CancelExecutionErrors];

export type CancelExecutionResponses = {
    /**
     * Execution cancelled
     */
    200: ExecutionResponse;
};

export type CancelExecutionResponse = CancelExecutionResponses[keyof CancelExecutionResponses];

export type ListAlertsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Filter by alert status
         */
        status?: 'open' | 'acknowledged' | 'resolved';
        /**
         * Filter by severity
         */
        severity?: 'info' | 'warning' | 'critical';
    };
    url: '/alerts';
};

export type ListAlertsErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListAlertsError = ListAlertsErrors[keyof ListAlertsErrors];

export type ListAlertsResponses = {
    /**
     * List of alerts
     */
    200: PaginatedAlerts;
};

export type ListAlertsResponse = ListAlertsResponses[keyof ListAlertsResponses];

export type CreateAlertData = {
    body: CreateAlertRequest;
    path?: never;
    query?: never;
    url: '/alerts';
};

export type CreateAlertErrors = {
    /**
     * Bad Request - Invalid input data
     */
    400: Error;
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type CreateAlertError = CreateAlertErrors[keyof CreateAlertErrors];

export type CreateAlertResponses = {
    /**
     * Alert created successfully
     */
    201: AlertResponse;
};

export type CreateAlertResponse = CreateAlertResponses[keyof CreateAlertResponses];

export type GetAlertData = {
    body?: never;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}';
};

export type GetAlertErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type GetAlertError = GetAlertErrors[keyof GetAlertErrors];

export type GetAlertResponses = {
    /**
     * Alert found
     */
    200: AlertResponse;
};

export type GetAlertResponse = GetAlertResponses[keyof GetAlertResponses];

export type AcknowledgeAlertData = {
    body?: never;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/acknowledge';
};

export type AcknowledgeAlertErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Cannot acknowledge - alert is already acknowledged or resolved
     */
    422: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type AcknowledgeAlertError = AcknowledgeAlertErrors[keyof AcknowledgeAlertErrors];

export type AcknowledgeAlertResponses = {
    /**
     * Alert acknowledged
     */
    200: AlertResponse;
};

export type AcknowledgeAlertResponse = AcknowledgeAlertResponses[keyof AcknowledgeAlertResponses];

export type ResolveAlertData = {
    body?: never;
    path: {
        /**
         * Resource UUID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/resolve';
};

export type ResolveAlertErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Cannot resolve - alert is already resolved
     */
    422: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ResolveAlertError = ResolveAlertErrors[keyof ResolveAlertErrors];

export type ResolveAlertResponses = {
    /**
     * Alert resolved
     */
    200: AlertResponse;
};

export type ResolveAlertResponse = ResolveAlertResponses[keyof ResolveAlertResponses];

export type ListAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Filter by event type
         */
        event_type?: string;
        /**
         * Filter by resource type
         */
        resource_type?: 'workflow' | 'execution' | 'alert';
        /**
         * Filter by action
         */
        action?: 'create' | 'update' | 'delete' | 'execute' | 'cancel' | 'acknowledge' | 'resolve';
    };
    url: '/audit-logs';
};

export type ListAuditLogsErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListAuditLogsError = ListAuditLogsErrors[keyof ListAuditLogsErrors];

export type ListAuditLogsResponses = {
    /**
     * List of audit logs
     */
    200: PaginatedAuditLogs;
};

export type ListAuditLogsResponse = ListAuditLogsResponses[keyof ListAuditLogsResponses];

export type ListAuditLogsByResourceData = {
    body?: never;
    path: {
        /**
         * Type of resource (workflow, execution, alert)
         */
        resourceType: 'workflow' | 'execution' | 'alert';
        /**
         * Resource UUID
         */
        resourceId: string;
    };
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/audit-logs/resource/{resourceType}/{resourceId}';
};

export type ListAuditLogsByResourceErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListAuditLogsByResourceError = ListAuditLogsByResourceErrors[keyof ListAuditLogsByResourceErrors];

export type ListAuditLogsByResourceResponses = {
    /**
     * List of audit logs for the resource
     */
    200: PaginatedAuditLogs;
};

export type ListAuditLogsByResourceResponse = ListAuditLogsByResourceResponses[keyof ListAuditLogsByResourceResponses];

export type ListAuditLogsByUserData = {
    body?: never;
    path: {
        /**
         * User UUID
         */
        userId: string;
    };
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/audit-logs/user/{userId}';
};

export type ListAuditLogsByUserErrors = {
    /**
     * Unauthorized - Missing or invalid authentication
     */
    401: Error;
    /**
     * Not Found - Resource does not exist
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListAuditLogsByUserError = ListAuditLogsByUserErrors[keyof ListAuditLogsByUserErrors];

export type ListAuditLogsByUserResponses = {
    /**
     * List of audit logs for the user
     */
    200: PaginatedAuditLogs;
};

export type ListAuditLogsByUserResponse = ListAuditLogsByUserResponses[keyof ListAuditLogsByUserResponses];
