// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Health check response
 */
export const zHealthStatus = z.object({
    status: z.enum([
        'healthy',
        'unhealthy',
        'degraded'
    ]),
    checks: z.record(z.object({
        status: z.string().optional(),
        message: z.string().optional()
    })).optional()
});

/**
 * Workflow status
 */
export const zWorkflowStatus = z.enum([
    'active',
    'inactive',
    'draft'
]);

/**
 * Workflow definition for orchestration
 */
export const zWorkflow = z.object({
    id: z.string().uuid(),
    tenant_id: z.string().uuid(),
    name: z.string().min(3).max(100),
    description: z.string().max(500).optional(),
    definition: z.record(z.unknown()),
    schedule: z.string().optional(),
    status: zWorkflowStatus,
    version: z.number().int().gte(1),
    created_by: z.string().uuid().optional(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

/**
 * Paginated list of workflows
 */
export const zPaginatedWorkflows = z.object({
    data: z.array(zWorkflow),
    total: z.number().int().gte(0),
    page: z.number().int().gte(1),
    limit: z.number().int().gte(1).lte(100)
});

/**
 * Error response
 */
export const zError = z.object({
    code: z.string(),
    message: z.string(),
    details: z.record(z.unknown()).optional()
});

/**
 * Request body for creating a workflow
 */
export const zCreateWorkflowRequest = z.object({
    name: z.string().min(3).max(100),
    description: z.string().max(500).optional(),
    definition: z.record(z.unknown()),
    schedule: z.string().optional()
});

/**
 * Single workflow response wrapper
 */
export const zWorkflowResponse = z.object({
    data: zWorkflow
});

/**
 * Request body for updating a workflow
 */
export const zUpdateWorkflowRequest = z.object({
    name: z.string().min(3).max(100).optional(),
    description: z.string().max(500).optional(),
    definition: z.record(z.unknown()).optional(),
    schedule: z.string().optional(),
    status: zWorkflowStatus.optional()
});

/**
 * Request body for executing a workflow
 */
export const zExecuteWorkflowRequest = z.object({
    input: z.record(z.unknown()).optional()
});

/**
 * Execution status
 */
export const zExecutionStatus = z.enum([
    'pending',
    'running',
    'completed',
    'failed',
    'cancelled'
]);

/**
 * Workflow execution instance
 */
export const zExecution = z.object({
    id: z.string().uuid(),
    tenant_id: z.string().uuid(),
    workflow_id: z.string().uuid(),
    temporal_workflow_id: z.string().optional(),
    temporal_run_id: z.string().optional(),
    status: zExecutionStatus,
    input: z.record(z.unknown()).optional(),
    output: z.record(z.unknown()).optional(),
    error: z.string().optional(),
    started_at: z.string().datetime().optional(),
    completed_at: z.string().datetime().optional(),
    created_by: z.string().uuid().optional(),
    created_at: z.string().datetime()
});

/**
 * Single execution response wrapper
 */
export const zExecutionResponse = z.object({
    data: zExecution
});

/**
 * Paginated list of executions
 */
export const zPaginatedExecutions = z.object({
    data: z.array(zExecution),
    total: z.number().int().gte(0),
    page: z.number().int().gte(1),
    limit: z.number().int().gte(1).lte(100)
});

/**
 * Alert severity level
 */
export const zAlertSeverity = z.enum([
    'info',
    'warning',
    'critical'
]);

/**
 * Alert status
 */
export const zAlertStatus = z.enum([
    'open',
    'acknowledged',
    'resolved'
]);

/**
 * System alert for workflow events
 */
export const zAlert = z.object({
    id: z.string().uuid(),
    tenant_id: z.string().uuid(),
    workflow_id: z.string().uuid().optional(),
    execution_id: z.string().uuid().optional(),
    severity: zAlertSeverity,
    title: z.string().max(200),
    message: z.string().optional(),
    status: zAlertStatus,
    acknowledged_at: z.string().datetime().optional(),
    acknowledged_by: z.string().uuid().optional(),
    resolved_at: z.string().datetime().optional(),
    resolved_by: z.string().uuid().optional(),
    created_at: z.string().datetime()
});

/**
 * Paginated list of alerts
 */
export const zPaginatedAlerts = z.object({
    data: z.array(zAlert),
    total: z.number().int().gte(0),
    page: z.number().int().gte(1),
    limit: z.number().int().gte(1).lte(100)
});

/**
 * Request body for creating an alert
 */
export const zCreateAlertRequest = z.object({
    workflow_id: z.string().uuid().optional(),
    execution_id: z.string().uuid().optional(),
    severity: zAlertSeverity,
    title: z.string().max(200),
    message: z.string().optional()
});

/**
 * Single alert response wrapper
 */
export const zAlertResponse = z.object({
    data: zAlert
});

/**
 * Audit log entry for tracking changes
 */
export const zAuditLog = z.object({
    id: z.string().uuid(),
    tenant_id: z.string().uuid(),
    user_id: z.string().uuid().optional(),
    event_type: z.string(),
    resource_type: z.string(),
    resource_id: z.string().uuid().optional(),
    action: z.string(),
    old_value: z.record(z.unknown()).optional(),
    new_value: z.record(z.unknown()).optional(),
    ip_address: z.string().optional(),
    user_agent: z.string().optional(),
    created_at: z.string().datetime()
});

/**
 * Paginated list of audit logs
 */
export const zPaginatedAuditLogs = z.object({
    data: z.array(zAuditLog),
    total: z.number().int().gte(0),
    page: z.number().int().gte(1),
    limit: z.number().int().gte(1).lte(100)
});

/**
 * Page number (1-based)
 */
export const zPageQuery = z.number().int().gte(1).default(1);

/**
 * Number of items per page
 */
export const zLimitQuery = z.number().int().gte(1).lte(100).default(20);

/**
 * Filter by workflow status
 */
export const zWorkflowStatusQuery = z.enum([
    'active',
    'inactive',
    'draft'
]);

/**
 * Search term
 */
export const zSearchQuery = z.string().max(100);

/**
 * Resource UUID
 */
export const zIdPath = z.string().uuid();

/**
 * Filter by execution status
 */
export const zExecutionStatusQuery = z.enum([
    'pending',
    'running',
    'completed',
    'failed',
    'cancelled'
]);

/**
 * Filter by alert status
 */
export const zAlertStatusQuery = z.enum([
    'open',
    'acknowledged',
    'resolved'
]);

/**
 * Filter by event type
 */
export const zEventTypeQuery = z.string();

/**
 * Type of resource (workflow, execution, alert)
 */
export const zResourceTypePath = z.enum([
    'workflow',
    'execution',
    'alert'
]);

/**
 * Resource UUID
 */
export const zResourceIdPath = z.string().uuid();

/**
 * User UUID
 */
export const zUserIdPath = z.string().uuid();

export const zHealthCheckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Service is healthy
 */
export const zHealthCheckResponse = zHealthStatus;

export const zLivenessProbeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Service is alive
 */
export const zLivenessProbeResponse = zHealthStatus;

export const zReadinessProbeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Service is ready
 */
export const zReadinessProbeResponse = zHealthStatus;

export const zListWorkflowsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number().int().gte(1).optional().default(1),
        limit: z.number().int().gte(1).lte(100).optional().default(20),
        status: z.enum([
            'active',
            'inactive',
            'draft'
        ]).optional(),
        search: z.string().max(100).optional()
    }).optional()
});

/**
 * List of workflows
 */
export const zListWorkflowsResponse = zPaginatedWorkflows;

export const zCreateWorkflowData = z.object({
    body: zCreateWorkflowRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Workflow created successfully
 */
export const zCreateWorkflowResponse = zWorkflowResponse;

export const zDeleteWorkflowData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * No Content - Successful operation with no response body
 */
export const zDeleteWorkflowResponse = z.void();

export const zGetWorkflowData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Workflow found
 */
export const zGetWorkflowResponse = zWorkflowResponse;

export const zUpdateWorkflowData = z.object({
    body: zUpdateWorkflowRequest,
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Workflow updated successfully
 */
export const zUpdateWorkflowResponse = zWorkflowResponse;

export const zExecuteWorkflowData = z.object({
    body: zExecuteWorkflowRequest.optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Execution started
 */
export const zExecuteWorkflowResponse = zExecutionResponse;

export const zListWorkflowExecutionsData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.object({
        page: z.number().int().gte(1).optional().default(1),
        limit: z.number().int().gte(1).lte(100).optional().default(20),
        status: z.enum([
            'pending',
            'running',
            'completed',
            'failed',
            'cancelled'
        ]).optional()
    }).optional()
});

/**
 * List of executions
 */
export const zListWorkflowExecutionsResponse = zPaginatedExecutions;

export const zListExecutionsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number().int().gte(1).optional().default(1),
        limit: z.number().int().gte(1).lte(100).optional().default(20),
        status: z.enum([
            'pending',
            'running',
            'completed',
            'failed',
            'cancelled'
        ]).optional()
    }).optional()
});

/**
 * List of executions
 */
export const zListExecutionsResponse = zPaginatedExecutions;

export const zGetExecutionData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Execution found
 */
export const zGetExecutionResponse = zExecutionResponse;

export const zCancelExecutionData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Execution cancelled
 */
export const zCancelExecutionResponse = zExecutionResponse;

export const zListAlertsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number().int().gte(1).optional().default(1),
        limit: z.number().int().gte(1).lte(100).optional().default(20),
        status: z.enum([
            'open',
            'acknowledged',
            'resolved'
        ]).optional(),
        severity: z.enum([
            'info',
            'warning',
            'critical'
        ]).optional()
    }).optional()
});

/**
 * List of alerts
 */
export const zListAlertsResponse = zPaginatedAlerts;

export const zCreateAlertData = z.object({
    body: zCreateAlertRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Alert created successfully
 */
export const zCreateAlertResponse = zAlertResponse;

export const zGetAlertData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Alert found
 */
export const zGetAlertResponse = zAlertResponse;

export const zAcknowledgeAlertData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Alert acknowledged
 */
export const zAcknowledgeAlertResponse = zAlertResponse;

export const zResolveAlertData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Alert resolved
 */
export const zResolveAlertResponse = zAlertResponse;

export const zListAuditLogsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number().int().gte(1).optional().default(1),
        limit: z.number().int().gte(1).lte(100).optional().default(20),
        event_type: z.string().optional(),
        resource_type: z.enum([
            'workflow',
            'execution',
            'alert'
        ]).optional(),
        action: z.enum([
            'create',
            'update',
            'delete',
            'execute',
            'cancel',
            'acknowledge',
            'resolve'
        ]).optional()
    }).optional()
});

/**
 * List of audit logs
 */
export const zListAuditLogsResponse = zPaginatedAuditLogs;

export const zListAuditLogsByResourceData = z.object({
    body: z.never().optional(),
    path: z.object({
        resourceType: z.enum([
            'workflow',
            'execution',
            'alert'
        ]),
        resourceId: z.string().uuid()
    }),
    query: z.object({
        page: z.number().int().gte(1).optional().default(1),
        limit: z.number().int().gte(1).lte(100).optional().default(20)
    }).optional()
});

/**
 * List of audit logs for the resource
 */
export const zListAuditLogsByResourceResponse = zPaginatedAuditLogs;

export const zListAuditLogsByUserData = z.object({
    body: z.never().optional(),
    path: z.object({
        userId: z.string().uuid()
    }),
    query: z.object({
        page: z.number().int().gte(1).optional().default(1),
        limit: z.number().int().gte(1).lte(100).optional().default(20)
    }).optional()
});

/**
 * List of audit logs for the user
 */
export const zListAuditLogsByUserResponse = zPaginatedAuditLogs;
